#!/usr/bin/env python3
"""Launch the XCZS ROS 2 sensor stream web service."""

import os
import sys


SCRIPT_DIRECTORY = os.path.dirname(os.path.abspath(__file__))
JIANG_DIRECTORY = os.path.dirname(SCRIPT_DIRECTORY)
sys.path.insert(0, JIANG_DIRECTORY)

from sensor_bridge.runner import main  # noqa: E402


if __name__ == "__main__":
    main()
