string control_id
string operation_lease_id
string robot_model
string robot_link
geometry_msgs/Point robot_grasp_point
string robot_base_link
bool attach
---
bool success
string message
float64 distance
