planning_plugin: ompl_interface/OMPLPlanner
start_state_max_bounds_error: 0.1
jiggle_fraction: 0.05
request_adapters: >-
  default_planner_request_adapters/AddTimeOptimalParameterization
  default_planner_request_adapters/ResolveConstraintFrames
  default_planner_request_adapters/FixWorkspaceBounds
  default_planner_request_adapters/FixStartStateBounds
  default_planner_request_adapters/FixStartStateCollision
  default_planner_request_adapters/FixStartStatePathConstraints

left_arm:
  planner_configs:
    - RRTConnect
    - RRTstar
    - PRMstar
  projection_evaluator: joints(l_arm_0_joint,l_arm_1_joint)
  longest_valid_segment_fraction: 0.005

right_arm:
  planner_configs:
    - RRTConnect
    - RRTstar
    - PRMstar
  projection_evaluator: joints(r_arm_0_joint,r_arm_1_joint)
  longest_valid_segment_fraction: 0.005

three_cylinder:
  planner_configs:
    - RRTConnect
  projection_evaluator: joints(r_three_cyl_finger1_joint,r_three_cyl_finger2_joint)
  longest_valid_segment_fraction: 0.01

two_cylinder:
  planner_configs:
    - RRTConnect
  projection_evaluator: joints(l_two_cyl_finger1_joint,l_two_cyl_finger2_joint)
  longest_valid_segment_fraction: 0.01

rocker:
  planner_configs:
    - RRTConnect
  projection_evaluator: joints(l_rocker_rotor_joint)
  longest_valid_segment_fraction: 0.01

rotate_button:
  planner_configs:
    - RRTConnect
  projection_evaluator: joints(r_rotbtn_jaw1_joint,r_rotbtn_jaw2_joint)
  longest_valid_segment_fraction: 0.01
